In [ ]:
   # ****part 1****

In [109]:
import numpy as np

In [5]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [57]:
print("Print array using numpy")
print("1D array")
a = np.array([1,2,3,4,5])
print(a)

print("2D array")
b = np.array([[1,2],[3,4],[5,6]])
print(b)

print("3D array")
c = np.array([[[1,2],[3,4],[5,6],[7,8],[9,10],[11,12],[13,14]]])
print(c)

Print array using numpy
1D array
[1 2 3 4 5]
2D array
[[1 2]
 [3 4]
 [5 6]]
3D array
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]
  [11 12]
  [13 14]]]


In [11]:
print(type(c))
print(type(b))
print(type(a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [12]:
#number of elements in array
print(a.size)
print(b.size)
print(c.size)

5
6
14


In [13]:
#shape(array,rows,cols)
print(a.shape)
print(b.shape)
print(c.shape)

(5,)
(3, 2)
(1, 7, 2)


In [16]:
d = np.array([[1,1.1,2,3],[4,4.5,6,7]])
print(d.dtype)

float64


In [18]:
print(d.transpose())

[[1.  4. ]
 [1.1 4.5]
 [2.  6. ]
 [3.  7. ]]


In [ ]:
        # ****part2****

In [21]:
# np.empty((rows,column),types)
np.empty((4,4),dtype = float)

array([[2.35541533e-312, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [2.14321575e-312, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [23]:
# np.ones((row,col),dtype)
x=np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [25]:
y=np.ones((5,9))
print(y)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [32]:
z = np.ones((2,2) , dtype = float)
print(z)
z

[[1. 1.]
 [1. 1.]]


array([[1., 1.],
       [1., 1.]])

In [31]:
# np.zeros((row,col),dtype)
x=np.zeros(2)
x

array([0., 0.])

In [33]:
y = np.ones((2,2))
y

array([[1., 1.],
       [1., 1.]])

In [35]:
z=np.ones((2,2), dtype = int)
z

array([[1, 1],
       [1, 1]])

In [38]:
z = np.ones((2,2), dtype = str)
print(z)

[['1' '1']
 ['1' '1']]


In [39]:
z = np.ones((2,2), dtype = bool)
print(z)
x = np.zeros((2,2),dtype = bool)
print(x)


[[ True  True]
 [ True  True]]
[[False False]
 [False False]]


In [ ]:
# *****Part3*****

In [40]:
#np.arange(start,end,step)

a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [41]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [46]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [47]:
#arr.reshape((row,col))

a = a.reshape((3,3))
print(a)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [48]:
b= np.arange(1,100,2)
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [51]:
b = b.reshape((10,5))
print(b)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]
 [51 53 55 57 59]
 [61 63 65 67 69]
 [71 73 75 77 79]
 [81 83 85 87 89]
 [91 93 95 97 99]]


In [52]:
b = b.flatten()
print(b)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [58]:
a = a.ravel()
print(a)

[1 2 3 4 5]


In [ ]:
#a.ravel() =
#1)return only reference/view of original array
#2) if you modify the array you would notice that the value of original array also changes
#3) ravel is faster than flatten() as it does nt occupy any memory.
#4) ravel is a library-level function

#a.flatten() :
#1) return copy of original array
#2) if you modify any value of this array value of original array is not affected
#3) flatten() is comparatively slower than ravel() as it occupies memory
#4) flatten is a method of an ndarray object

In [ ]:
#************part4**********

In [62]:
a = np.arange(1,10)
a = np.reshape(a,(3,3))
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
a[0]

array([1, 2, 3])

In [64]:
a[0,0]

np.int64(1)

In [66]:
a[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [69]:
a[: , 1]

array([2, 5, 8])

In [70]:
a[1:2,2]

array([6])

In [71]:
a[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
a[: , 0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [73]:
a[:,0:2].dtype

dtype('int64')

In [ ]:
#**********part5**********

In [77]:
a = np.arange(0,18).reshape((6,3))
b = np.arange(20,38).reshape((6,3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [78]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [79]:
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [80]:
a-b

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [81]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [82]:
a*b

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [83]:
np.multiply(a,b)

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [84]:
a/b

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [85]:
np.divide(a,b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [87]:
print(a.shape)
print(b.shape)

(6, 3)
(6, 3)


In [89]:
b = b.reshape((3,6))

In [90]:
a@b

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [91]:
a.dot(b)

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [96]:
b.max()


np.int64(37)

In [94]:
b.min()

np.int64(20)

In [95]:
b.argmax()

np.int64(17)

In [97]:
np.sum(b)

np.int64(513)

In [98]:
np.sum(b,axis = 1)

array([135, 171, 207])

In [99]:
np.sum(b,axis = 0)

array([78, 81, 84, 87, 90, 93])

In [101]:
np.mean(b)

np.float64(28.5)

In [102]:
np.sqrt(b)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253]])

In [103]:
np.std(b)

np.float64(5.188127472091127)

In [104]:
np.log(b)

array([[2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738,
        3.4339872 ],
       [3.4657359 , 3.49650756, 3.52636052, 3.55534806, 3.58351894,
        3.61091791]])

In [ ]:
#***********part6***********

In [1]:
import matplotlib.pyplot as plt
plt.style.use('background')

ModuleNotFoundError: No module named 'matplotlib'

In [111]:
np.pi

3.141592653589793

In [112]:
np.sin(np.pi/2)

np.float64(1.0)

In [113]:
np.sin(np.pi/6)

np.float64(0.49999999999999994)

In [114]:
np.cos(np.pi/2)

np.float64(6.123233995736766e-17)

In [115]:
np.cos(np.pi/6)

np.float64(0.8660254037844387)

In [116]:
np.tan(np.pi/2)

np.float64(1.633123935319537e+16)

In [117]:
np.tan(0)

np.float64(0.0)

In [ ]:
#***********part7************

In [120]:
np.random.random(1)

array([0.32437157])

In [122]:
np.random.random(2)

array([0.54239603, 0.08950637])

In [123]:
np.random.random((2,2))

array([[0.54284961, 0.86936158],
       [0.867853  , 0.10908612]])

In [126]:
np.random.randint((1,10))

array([0, 5], dtype=int32)

In [128]:
np.random.randint(1,10,(2,2))

array([[1, 4],
       [5, 3]], dtype=int32)

In [130]:
np.random.randint(1,10,(3,4,5))

array([[[9, 1, 6, 3, 3],
        [1, 8, 4, 7, 6],
        [9, 2, 7, 8, 4],
        [1, 6, 4, 9, 7]],

       [[6, 9, 2, 9, 4],
        [8, 8, 3, 4, 9],
        [8, 5, 8, 6, 4],
        [6, 3, 6, 9, 1]],

       [[4, 8, 2, 9, 6],
        [1, 4, 5, 1, 3],
        [7, 3, 2, 9, 9],
        [8, 6, 2, 3, 3]]], dtype=int32)

In [132]:
np.random.rand(2,2)

array([[0.26676158, 0.10096998],
       [0.03733013, 0.01097626]])

In [133]:
np.random.randn(2,2)

array([[-0.19153654, -1.08805696],
       [ 1.19476221, -1.27199809]])

In [134]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [136]:
np.random.choice(a)

np.int64(4)

In [ ]:
#********part8*******

In [137]:
s1 = 'isha is my name'
s2 = 'i am AN indian'

In [142]:
np.char.lower(s2)

array('i am an indian', dtype='<U14')

In [138]:
np.char.add(s1, s2)

np.str_('isha is my namei am an indian')

In [140]:
np.char.upper(s1)

array('ISHA IS MY NAME', dtype='<U15')

In [143]:
np.char.split(s1)

array(list(['isha', 'is', 'my', 'name']), dtype=object)

In [144]:
s3 = 'isha is my\nname'
np.char.splitlines(s3)

array(list(['isha is my', 'name']), dtype=object)

In [145]:
np.char.replace(s1,'name','sirname')

array('isha is my sirname', dtype='<U18')

In [146]:
print('*******good bye******')

*******good bye******


In [152]:
print(np.char.center('good bye' , 18 , '*'))

*****good bye*****
